PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dc: <http://purl.org/dc/terms/>
PREFIX social: <http://users.dcc.uchile.cl/~ahogan/social.ttl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX appearances: <http://rdf.muninn-project.org/ontologies/appearances>

# Q2a
LOAD <http://raw.githubusercontent.com/davidrojas0791/Web-Datos-Lab9/master/foaf.ttl#dr> .


# Q2b
SELECT (count(*) as ?triples) WHERE { 
    GRAPH <http://raw.githubusercontent.com/davidrojas0791/Web-Datos-Lab9/master/foaf.ttl> { ?s ?p ?o }
}

# Q2c
construct{ 
    ?me social:unlikelyFriendOf ?newFriends 
} 
where {
    GRAPH <http://raw.githubusercontent.com/davidrojas0791/Web-Datos-Lab9/master/foaf.ttl> { 
        ?me a foaf:Person .
        ?me social:hasEnemy ?enemies .
        ?enemies foaf:knows ?newFriends .
    } 
}

insert data {
    graph <http://raw.githubusercontent.com/davidrojas0791/Web-Datos-Lab9/master/foaf.ttl> {
        select ?me social:unlikelyFriendOf ?newFriends
        where {
            GRAPH <http://raw.githubusercontent.com/davidrojas0791/Web-Datos-Lab9/master/foaf.ttl> { 
                ?me a foaf:Person .
                ?me social:hasEnemy ?enemies .
                ?enemies foaf:knows ?newFriends .
            } 
        }
    }
}

INSERT { 
    GRAPH <urn:sparql:tests:insert:informative2> { ?me social:unlikelyFriendOf ?newFriends } 
} where {
    GRAPH <http://raw.githubusercontent.com/davidrojas0791/Web-Datos-Lab9/master/foaf.ttl> { 
        ?me a foaf:Person .
        ?me social:hasEnemy ?enemies .
        ?enemies foaf:knows ?newFriends .
    } 
}


# Q2d

# Q2e 

# Q2f

# Q2g