PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dc: <http://purl.org/dc/terms/>
PREFIX social: <http://users.dcc.uchile.cl/~ahogan/social.ttl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX appearances: <http://rdf.muninn-project.org/ontologies/appearances>

# Q2a
LOAD <http://raw.githubusercontent.com/davidrojas0791/Web-Datos-Lab9/master/foaf.ttl>


# Q2b
SELECT (count(*) as ?triples) WHERE { 
    graph <http://raw.githubusercontent.com/davidrojas0791/Web-Datos-Lab9/master/foaf.ttl> {
        ?s ?p ?o
    }
}

# Q2c
insert {
    graph <http://raw.githubusercontent.com/davidrojas0791/Web-Datos-Lab9/master/foaf.ttl> { ?me social:unlikelyFriendOf ?unlikelyFriend . }
} where {
    graph <http://raw.githubusercontent.com/davidrojas0791/Web-Datos-Lab9/master/foaf.ttl> {
        ?me a foaf:Person .
        ?me social:hasEnemy ?enemies.
        graph ?g { ?enemies foaf:knows ?unlikelyFriend .}
    }
}

# Q2d
delete {
    graph <http://raw.githubusercontent.com/davidrojas0791/Web-Datos-Lab9/master/foaf.ttl> { ?me social:unlikelyFriendOf ?unlikelyFriend . }
} where {
    graph <http://raw.githubusercontent.com/davidrojas0791/Web-Datos-Lab9/master/foaf.ttl> {
        ?me a foaf:Person .
        ?me social:unlikelyFriendOf ?unlikelyFriend .
    }
}

# Q2e 
insert {
    graph <http://raw.githubusercontent.com/davidrojas0791/Web-Datos-Lab9/master/foaf.ttl> { ?interests ?p ?o }
} where {
    graph <http://raw.githubusercontent.com/davidrojas0791/Web-Datos-Lab9/master/foaf.ttl> {
        ?me a foaf:Person .
        ?me foaf:interest ?interests.
        graph ?g { 
            ?interests ?p ?o .
            ?interests wdt:P31 ?type .
            filter(?type = wd:Q11424)
        }
    }
}

# Q2f
select  distinct ?peopleName ?moviesTheyLiked ?theirType ?theirTypeName ?moviesTheyLikedName
where {
    graph <http://raw.githubusercontent.com/davidrojas0791/Web-Datos-Lab9/master/foaf.ttl> {
        ?me a foaf:Person .
        ?me foaf:knows* ?people .
        ?me foaf:interest ?moviesLiked .
        graph ?e {
            ?moviesLiked wdt:P31 ?type .
            ?moviesLiked wdt:P57 ?director .
        }
        graph ?g {
            ?people foaf:name ?peopleName .
            ?people foaf:interest ?moviesTheyLiked .
            graph ?f { 
                ?moviesTheyLiked wdt:P31 ?theirType .
                ?moviesTheyLiked wdt:P57 ?theirDirector .
                ?moviesTheyLiked rdfs:label ?moviesTheyLikedName .
                ?theirType rdfs:label ?theirTypeName.
                filter(?theirType = wd:Q11424)
                filter(lang(?moviesTheyLikedName) = 'en')
                filter(lang(?theirTypeName) = 'en')
                filter(?theirDirector = ?director)
            }
        }
    }
}

# Q2g
select ?people ?peopleName ?game ?gameName
where {
    service <https://query.wikidata.org/bigdata/namespace/wdq/sparql> {
        ?game wdt:P31 wd:Q7889 .
        ?game wdt:P31 wd:Q215206 .
        ?game rdfs:label ?gameName .
        filter(lang(?gameName)='en')
    }
    graph <http://raw.githubusercontent.com/davidrojas0791/Web-Datos-Lab9/master/foaf.ttl> {
        ?me a foaf:Person .
        ?me foaf:knows ?people .
        graph ?g {
            ?people rdfs:label ?peopleName .
            ?people foaf:interest ?npCGame .
            filter(?game = ?npCGame)
        }
    }
}